### ISSUE TITLE
New build instructions needed  - existing not apply

### ISSUE THREAD

**Issue by dariusp2008** [ipop-project/Tincan#2]
Hello,
I saw that development of this great piece of software is still active. Both for the executable and for the controller.
Building the binary for the new WIP2 tincan was not succesfull for me...
Please - an important part of any successful develompent - is to have documentation to build and test on different platforms. I please kcratie which is a great developer to have a few hours to write an updated buil tutorial for the ipop-tincan binary on generic linux platform.
Many thanks!

**Comment by kcratie** [comment]
The Tincan build instructions have been [updated](https://github.com/ipop-project/ipop-project.github.io/wiki/Building-the-Code).

**Comment by dariusp2008** [comment]
Thank you for your effort. You are doing a really, really great job!
